# Repos you want to receive files from LearningSessions
# Use HTTPS form owner/repo; private repos require a PAT with repo scope.

group:
  repos: |
    Greg-T8/LearningTopic
  files:
    - source: templates/common/          # in LearningSessions
      dest:   .learning/shared/          # in each target repo
      exclude:
        - "**/*.tmp"
        - "**/.DS_Store"
    - source: .github/ISSUE_TEMPLATE/    # share issue templates
      dest:   .github/ISSUE_TEMPLATE/
    - source: .github/pull_request_template.md
      dest:   .github/pull_request_template.md
    - source: scripts/                   # share PowerShell helpers
      dest:   scripts/
