# Repos you want to receive files from LearningSessions
# Use HTTPS form owner/repo; private repos require a PAT with repo scope.

group:
  - files:
      - source: workflows/automerge.yml
        dest: .github/workflows/automerge.yml
      - source: templates/issues/lab.yml
        dest: .github/issues/lab.yml
      - source: templates/issues/topic.yml
        dest: .github/issues/topic.yml
      - source: .markdownlint.yml
        dest: .markdownlint.yml
    repos: |
      Greg-T8/LearningTopic

  # - files: # Example of another group
  #     - source: templates/pull_request_template.md
  #       dest: .github/pull_request_template.md
  #   repos: |
