# Repos you want to receive files from LearningSessions

group:
  - files:
      - source: .markdownlint.yml
        dest: .markdownlint.yml

      - source: templates/workflows/automerge.yml
        dest: .github/workflows/automerge.yml
        deleteOrphaned: true

      - source: templates/issues/
        dest: .github/ISSUE_TEMPLATE/
        deleteOrphaned: true

      - source: templates/markdown/
        dest: .lab/templates/
        deleteOrphaned: true

      - source: templates/pull_requests/
        dest: .github/PULL_REQUEST_TEMPLATE/
        deleteOrphaned: true

      - source: tools/
        dest: .lab/tools/
        deleteOrphaned: true

    repos: |
      Greg-T8/LearningTopic

  # - files: # Example of another group
  #     - source: templates/pull_request_template.md
  #       dest: .github/pull_request_template.md
  #   repos: |
