# Repos you want to receive files from LearningSessions
# Use HTTPS form owner/repo; private repos require a PAT with repo scope.

group:
  repos: |
    Greg-T8/LearningTopic
  files:
    - source: templates/issues/lab.yml
      dest:   .github/issues/lab.yml
